export const DISCOVERY_UDP_PORT = 41234;

export const DISCOVERY_MESSAGE_TYPE = 'HFCL_MAIN_SERVER' as const;

export const DISCOVERY_PROTOCOL_VERSION = 1;

export const DISCOVERY_BROADCAST_INTERVAL_MS = Number(
  process.env.HFCL_DISCOVERY_BROADCAST_INTERVAL_MS ?? 3000,
);

export const DISCOVERY_FALLBACK_BROADCAST_ADDRESS = '255.255.255.255';
